package models.utils;

import models.Semesters;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Created by Martin on 16.04.2017.
 */
public class Countries {
    public static List<String> countriesList() {
        List<String> countries = new ArrayList<String>();
        countries.add("AFGHANISTÁN");
        countries.add("ALBÁNIE");
        countries.add("ALŽÍR");
        countries.add("AMERISKÁ SAMOA");
        countries.add("ANGOLA");
        countries.add("ANGUILLA");
        countries.add("ANTIGUA A BARBUDA");
        countries.add("ARGENTINA");
        countries.add("ARMENIE");
        countries.add("ARUBA");
        countries.add("AUSTRÁLIE");
        countries.add("AZERBÁJDŽÁN");
        countries.add("BAHAMY");
        countries.add("BAHRAJN");
        countries.add("BANGLADÉŠ");
        countries.add("BARBADOS");
        countries.add("BELGIE");
        countries.add("BELIZE");
        countries.add("BĚLORUSKO");
        countries.add("BENIN");
        countries.add("BHUTAN");
        countries.add("BOLÍVIE");
        countries.add("BOSNA A HERCEGOVINA");
        countries.add("BOTSWANA");
        countries.add("BRAZÍLIE");
        countries.add("BRITSKÉ PANENSKÉ OSTROVY");
        countries.add("BRUNEI DARUSSALAM");
        countries.add("BULHARSKO");
        countries.add("BURKINA FASO");
        countries.add("BURUNDI");
        countries.add("COMOROS");
        countries.add("COOKOVY OSTROVY");
        countries.add("CURACAO");
        countries.add("ČAD");
        countries.add("ČESKÁ REPUBLIKA");
        countries.add("ČILE");
        countries.add("ČÍNA");
        countries.add("DÁNSKO");
        countries.add("DOMINIKA");
        countries.add("DOMINIKÁNSKÁ REP.");
        countries.add("DŽIBUTSKO");
        countries.add("EGYPT");
        countries.add("EKVÁDOR");
        countries.add("ERITREA");
        countries.add("ESTONSKO");
        countries.add("ETIOPIE");
        countries.add("FALKLANDSKÉ OSTROVY");
        countries.add("FIDŽI");
        countries.add("FILIPÍNY");
        countries.add("FINSKO");
        countries.add("FRANCIE");
        countries.add("FRANCOUZSKÁ GUIANA");
        countries.add("FRANCOUZSKÁ POLYNÉZIE");
        countries.add("GABON");
        countries.add("GAMBIE");
        countries.add("GHANA");
        countries.add("GIBRALTAR");
        countries.add("GRENADA");
        countries.add("GRUZIE");
        countries.add("GUADELOUPE");
        countries.add("GUAM");
        countries.add("GUATEMALA");
        countries.add("GUINEA");
        countries.add("GUINEA BISSAU");
        countries.add("GUYANA");
        countries.add("HAITI");
        countries.add("HONDURAS");
        countries.add("HONG KONG");
        countries.add("CHORVATSKO");
        countries.add("INDIE");
        countries.add("INDONÉZIE");
        countries.add("IRÁK");
        countries.add("IRSKO");
        countries.add("ISLAND");
        countries.add("ITÁLIE");
        countries.add("IZRAEL");
        countries.add("JAMAICA");
        countries.add("JAPONSKO");
        countries.add("JEMEN");
        countries.add("JIŽNÍ KOREA");
        countries.add("JORDÁNSKO");
        countries.add("KAJMANSKÉ OSTROVY");
        countries.add("KAMBODŽA");
        countries.add("KAMERUN");
        countries.add("KANADA");
        countries.add("KAPVERDY");
        countries.add("KATAR");
        countries.add("KAZACHSTÁN");
        countries.add("KEŇA");
        countries.add("KIRIBATI");
        countries.add("KOLUMBIE");
        countries.add("KONGO");
        countries.add("KONGO DEM. REP.");
        countries.add("KOSOVO");
        countries.add("KOSTARIKA");
        countries.add("KUWAIT");
        countries.add("KYPR");
        countries.add("KYPR (SEVERNÍ)");
        countries.add("KYRGYZSTÁN");
        countries.add("LAOS");
        countries.add("LIBANON");
        countries.add("LIBÉRIE");
        countries.add("LIBYE");
        countries.add("LICHTENŠTEJNSKO");
        countries.add("LITVA");
        countries.add("LOTYŠSKO");
        countries.add("LUCEMBURSKO");
        countries.add("MACAU");
        countries.add("MADAGASKAR");
        countries.add("MAĎARSKO");
        countries.add("MAKEDONIE");
        countries.add("MALAJSIE");
        countries.add("MALAWI");
        countries.add("MALEDIVY");
        countries.add("MALI");
        countries.add("MALTA");
        countries.add("MAROKO");
        countries.add("MARŠALOVY OSTROVY");
        countries.add("MARTINIK");
        countries.add("MAURETÁNIE");
        countries.add("MAURÍCIUS");
        countries.add("MEXIKO");
        countries.add("MOLDÁVIE");
        countries.add("MONAKO");
        countries.add("MONGOLSKO");
        countries.add("MONTSERRAT");
        countries.add("MOZAMBIK");
        countries.add("NĚMECKO");
        countries.add("NEPÁL");
        countries.add("NIGER");
        countries.add("NIGÉRIE");
        countries.add("NIKARAGUA");
        countries.add("NIUE");
        countries.add("NIZOZEMÍ");
        countries.add("NORSKO");
        countries.add("NOVÁ KALEDONIE");
        countries.add("NOVÝ ZÉLAND");
        countries.add("OMÁN");
        countries.add("PÁKISTÁN");
        countries.add("PALESTINSKÁ ÚZEMÍ");
        countries.add("PANAMA");
        countries.add("PANENSKÉ OSTROVY");
        countries.add("PAPUA NOVÁ GUINEA");
        countries.add("PARAGUAY");
        countries.add("PERU");
        countries.add("POBŘEŽÍ SLONOVINY");
        countries.add("POLSKO");
        countries.add("PORTORIKO");
        countries.add("PORTUGALSKO");
        countries.add("RAKOUSKO");
        countries.add("RÉUNION");
        countries.add("ROVNÍKOVÁ GUINEA");
        countries.add("RUMUNSKO");
        countries.add("RUSKO");
        countries.add("RWANDA");
        countries.add("ŘECKO");
        countries.add("S. KITTS A NEVIS");
        countries.add("S. LUCIE");
        countries.add("S. MAARTEN");
        countries.add("S. MARTIN");
        countries.add("S. TOMÁŠ");
        countries.add("S. VINCENT");
        countries.add("SALVADOR");
        countries.add("SAMOA");
        countries.add("SAUDSKÁ ARÁBIE");
        countries.add("SENEGAL");
        countries.add("SEVERNÍ MARIÁNSKÉ OSTROVY");
        countries.add("SIERRA LEONE");
        countries.add("SINGAPUR");
        countries.add("SLOVENSKO");
        countries.add("SLOVINSKO");
        countries.add("SPOJENÉ ARABSKÉ EMIRÁTY");
        countries.add("SPOJENÉ STÁTY AMERICKÉ");
        countries.add("SRBSKO A ČERNÁ HORA");
        countries.add("SRÍ LANKA");
        countries.add("STŘEDOAFRICKÁ REPUBLIKA");
        countries.add("SUDAN");
        countries.add("SURINAM");
        countries.add("SÝRIE");
        countries.add("ŠALAMOUNOVY OSTR.");
        countries.add("ŠPANĚLSKO");
        countries.add("ŠVÉDSKO");
        countries.add("ŠVÝCARSKO");
        countries.add("TADŽIKISTÁN");
        countries.add("TAIWAN");
        countries.add("TANZÁNIE");
        countries.add("THAJSKO");
        countries.add("TOGO");
        countries.add("TONGA");
        countries.add("TRINIDAD A TOBAGO");
        countries.add("TUNISKO");
        countries.add("TURECKO");
        countries.add("TURKMENISTAN");
        countries.add("TURKS A CICOS");
        countries.add("TUVALU");
        countries.add("UGANDA");
        countries.add("UKRAJINA");
        countries.add("URUGUAY");
        countries.add("UZBEKISTÁN");
        countries.add("VANUATU");
        countries.add("VELKÁ BRITÁNIE");
        countries.add("VENEZUELA");
        countries.add("VIETNAM");
        countries.add("VÝCHODNÍ TIMOR");
        countries.add("ZAMBIE");
        countries.add("ZIMBABWE");
        return countries;
    }

    public static Map<String, String> options() {
        List<String> countriesL = Countries.countriesList();
        LinkedHashMap<String, String> options = new LinkedHashMap<String, String>();
        for (String set : countriesL) {
            options.put(set, set);
        }
        return options;
    }
}
